branches:
  only:
    - master
    - test-ci
image:
  - Visual Studio 2019
  - Ubuntu
  - macOS
init:
  - git config --global core.autocrlf true

environment:
  matrix:
    - nodejs_version: 9
    - nodejs_version: 8

for:
  - matrix:
      only:
        - image: Visual Studio 2019
    install:
      - ps: Install-Product node $env:nodejs_version
    test_script:
      - node --version
      - npm --version
      - npm test

  - matrix:
      only:
        - image: macOS
    install:
      - nvm use $nodejs_version
    test_script:
      - node --version
      - npm --version
      - npm test

  - matrix:
      only:
        - image: Ubuntu
    install:
      - nvm use $nodejs_version
    test_script:
      - node --version
      - npm --version
      - if [[ ${nodejs_version} != 15 ]]; then npm run test; fi;
      - if [[ ${nodejs_version} == 15 ]]; then npm run coverage; npx codecov; fi;

build: off
